pipeline {
	agent any
	tools {
		nodejs "MyNode"
	}
	stages {
		stage("Check Node Version"){
			steps{
				sh "node --version"
			}
		}
		stage("Install Dependencies"){
			steps{
				sh "npm --version"
				sh "npm install"
			}
		}
		stage("Test"){
			steps{
				sh "node Jenkins_Pipeline_Docker/app.js"
			}
		}
		stage("Release"){
			steps{
				echo "Releasing this version"
			}
		}
	}
}